version: '3.8'
services:
  app:
    build: .
    container_name: the-games-db_c
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: ['npm', 'run', 'dev']
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - ./prisma/data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
